//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentGoodsShippingDocument
    {
        public int idContentGoodsShippingDocument { get; set; }
        public int ShippingDocument_ShippingDocumentNumber { get; set; }
        public string Goods_GoodsName { get; set; }
        public Nullable<byte> QuantityGoods { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual ShippingDocument ShippingDocument { get; set; }
    }
}
