//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingDocument()
        {
            this.ContentGoodsShippingDocument = new HashSet<ContentGoodsShippingDocument>();
        }
    
        public int ShippingDocumentNumber { get; set; }
        public short Warehouse_WarehouseNumber { get; set; }
        public Nullable<System.DateTime> UnloadingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentGoodsShippingDocument> ContentGoodsShippingDocument { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
