//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseApp.Models
{
    using System;
    
    public partial class listGoodsQuant_Result
    {
        public short WarehouseNumber { get; set; }
        public string GoodsName { get; set; }
        public Nullable<int> Quant { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
