//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContentGoodsWaybill
    {
        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Номер должен быть положительным числом")]
        public int idContentGoodsWaybill { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Номер должен быть положительным числом")]
        public int Waybill_WaybillNumber { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "{0} длина должна быть между {2} и {1}.", MinimumLength = 2)]
        public string Goods_GoodsName { get; set; }

        [Required]
        [Range(0, 255, ErrorMessage = "Номер должен быть положительным числом до 255")]
        public byte QuantityGoods { get; set; }

        public virtual Goods Goods { get; set; }
        public virtual Waybill Waybill { get; set; }
    }
}
